### ISSUE TITLE
vs2015编译问题

### ISSUE THREAD

**Issue by Andrawzyf** [xuxu116/person_detection_lite#2]
你好，请问我在vs2015编译，在177行出现了问题vector<float> base_box = {0.0, 0.0, STRIDE[i] - 1.0, STRIDE[i] - 1.0};问题 	从 "double" 到 "float" 进行收缩转换无效，这个是啥问题呢？

**Comment by xuxu116** [comment]
这里类型转换只是报warning吧……
建议用的c++11编译

**Comment by Andrawzyf** [comment]
@xuxu116 是错误的。。。头大。。还有我查了一下怎么设置C++11  右键--》属性--》配置属性--》C/C++ 右边 C++语言标准 C++11 改为C89    ，但是我的VS2015没有C++语言标准这个选项。。
